### ISSUE TITLE
Dúvida com relação a `emitter.on('log', (message) => {}`

### ISSUE THREAD

**Issue by biangomes** [webacademyufac/programacao-avancada-backend-t2#2]
A minha dúvida é se  o uso do método `on` passando o `'log', (message)` como parâmetros define que o `log` é o evento que deve aguardar ser emitido ou ele é a função de callback?

Estudando por alguns materiais vi um exemplo de `EventEmitter` passando como parâmetro o evento em si e o segundo parâmetro uma função de callback. Nesse cenário do `project-logger/logger.js`:

- `'log'` é apenas um parâmetro qualquer e não uma função de callback?
- `'log'` **não** é um parâmetro qualquer, mas sim uma função de callback que está declarada em `function log(message)`?
- `(message)` é uma função anônima e de callback?

**Comment by vrcvieira** [comment]
Oi, Beatriz!
Toda vez que `log` aparece dentro de aspas simples, refere-se ao termo como string, mesmo. Quando aparece fora, está referenciando a função que criamos, que tem esse nome. No fim das contas, não foi um nome muito intuitivo pq confunde até com o método `log()` do objeto `console`.
O `message` parâmetro da função `log` que criamos é um parâmetro que recebe um texto e printa ele no console (o caminho é um pouco chato de entende, mas se vc seguir desde a chamada da função log, vai pegar).
Se ainda tiver dúvidas, reabre que vamos conversando, ok?
