### ISSUE TITLE
error: failed to push some refs 

### ISSUE THREAD

**Issue by biangomes** [webacademyufac/programacao-avancada-backend-t2#5]
Criei dois zip's pra colocar na minha pasta, mas ao tentar fazer o push enfrento esse problema:

`error: failed to push some refs to 'https://github.com/biangomes/programacao-avancada-backend-t2.git`. Esse é o fork criado.

![image](https://user-images.githubusercontent.com/20216893/206790903-df643f1c-9f42-4e6f-8008-35fb872f3c9b.png)

Diante desse cenário, existe sugestão de como posso fazer?

**Comment by jnognet** [comment]
@biangomes Observa que na terceira linha de erro ele fala que excedeu o limite de 100MB pois teu zip tem 132MB.
Verifica se esses links ajudam: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage

**Comment by biangomes** [comment]
@jnognet obrigada pelo apoio. Eu li o artigo "About large files on GitHub" e entendi que para conseguir subir arquivos +100Mb deve ser por meio de Git LFS. Propus adicionar o professor @vrcvieira como colaborador dos repositórios. A partir de amanhã eu vejo sobre o Git LFS e vejo se é viável.

Mais uma vez, obrigada!!

**Comment by vrcvieira** [comment]
Oi, Beatriz! Verifica quais docs dentro do repositório estão gerando esse tamanho. A priori, penso que pode ser o pdf vindo pelo seu repositório (nesse caso, pode deletá-lo). Veja também se o gitignore está correto, desconsiderando node_modules. Abraços!
